### ISSUE TITLE
error: duplicate value for resource 'attr/strokeWidth' with config ''

### ISSUE THREAD

**Issue by Tsabary** [emre1512/CircleProgressBar#8] opened 2019-04-08 22:27 UTC
Can't build the project, getting the following error

java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  C:\Users\Yanay\.gradle\caches\transforms-1\files-1.1\jetified-circleprogressbar-1.0.4.aar\0fe22733a8a04170d80035415cb5406a\res\values\values.xml:6:5-533: AAPT: error: duplicate value for resource 'attr/strokeWidth' with config ''.
      
  C:\Users\Yanay\.gradle\caches\transforms-1\files-1.1\jetified-circleprogressbar-1.0.4.aar\0fe22733a8a04170d80035415cb5406a\res\values\values.xml:6:5-533: AAPT: error: resource previously defined here.

**Comment by hetsgandhi** [comment] 2019-04-20 06:24
Even i am getting the same error! Please need help asap.

Thank you in advance

**Comment by cv0cv0** [comment] 2019-05-23 00:31
Me too.

**Comment by emre1512** [comment] 2019-06-06 03:39
Didn't tested yet but this issue should be handled by commit 8166fb16643a8d0132d9805af7904111dcf107c2

**Comment by allan-on** [comment] 2019-06-20 12:46
Hi. This issue isn't fixed in the version specified in the README (1.0.4) 
Still encountering -> ```Android resource compilation failed``` due to the same bug

**Comment by AkAndroid** [comment] 2019-09-05 05:14
hi, this issue isnt fixed yet, please give a solution on this , if possible.

**Comment by allan-on** [comment] 2019-09-05 07:40
@AkAndroid You can check out my fix here https://github.com/emre1512/CircleProgressBar/pull/9

**Comment by jomarierafa** [comment] 2019-09-05 09:21
hello please update the library, i got the same error , thanks

com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  C:\Users\OA-JomRafa\.gradle\caches\transforms-2\files-2.1\29204a68ef067df083cd438d66f53a13\res\values\values.xml:6:5-533: AAPT: error: duplicate value for resource 'attr/strokeWidth' with config ''.
      
  C:\Users\OA-JomRafa\.gradle\caches\transforms-2\files-2.1\29204a68ef067df083cd438d66f53a13\res\values\values.xml:6:5-533: AAPT: error: resource previously defined here.
      
  C:\Users\OA-JomRafa\AndroidStudioProjects\ForexApp\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml: error: file failed to compile.

**Comment by allan-on** [comment] 2019-09-05 09:32
I submitted a pull request which if merged will fix the issue but the author hasn't done that and looks like they aren't active in maintaining the library. You can clone or fork from my fix and use that and it should work

**Comment by emre1512** [comment] 2019-09-05 10:37
Hi, Sorry for the inconvinience, I am too busy. I will fix the issue as soon as possible. I will merge the pull requests without testing them (bad idea but I have no time). Then I will update the gradle dependency statement.

**Comment by allan-on** [comment] 2019-09-05 12:01
Cool. No worries. I can handle any other fixes for any other issues if they do come up :+1:

**Comment by amsakthi83** [comment] 2019-09-14 02:57
Hi Mr. Emre Deverci, Please fix the issues and commit the changes in GitHub as soon as possible. My app is in production so i need to fix this issue immediately and deploy.

**Comment by amsakthi83** [comment] 2019-09-14 02:57
> Hi, Sorry for the inconvinience, I am too busy. I will fix the issue as soon as possible. I will merge the pull requests without testing them (bad idea but I have no time). Then I will update the gradle dependency statement.

Hi Mr. Emre Deverci, Please fix the issues and commit the changes in GitHub as soon as possible. My app is in production so i need to fix this issue immediately and deploy.

**Comment by allan-on** [comment] 2019-09-14 08:21
Hi @amsakthi83 I think he merged a PR with fixes for the issue. Are you using the latest code?

**Comment by emre1512** [comment] 2019-09-14 15:47
I am working on it, trying to upload the library to bintray.

**Comment by amsakthi83** [comment] 2019-09-15 04:14
> I am working on it, trying to upload the library to bintray.

Please let me know when i can expect ? Approximate time?

**Comment by amsakthi83** [comment] 2019-09-16 07:59
> > I am working on it, trying to upload the library to bintray.
> 
> Please let me know when i can expect ? Approximate time?

Can you please upload bug fixes in git?

**Comment by amsakthi83** [comment] 2019-09-17 06:02
> Hi @amsakthi83 I think he merged a PR with fixes for the issue. Are you using the latest code?

Please help me is this issue fixed?

**Comment by amsakthi83** [comment] 2019-09-17 06:03
> > > I am working on it, trying to upload the library to bintray.
> > 
> > 
> > Please let me know when i can expect ? Approximate time?
> 
> Can you please upload bug fixes in git?

Can you please let me know when it will be solved and released?

**Comment by emre1512** [comment] 2019-10-05 20:19
Hi, I fixed the issue and upload the newest version of library to bintray. Please check the main page.

Please let me know if the issue is fixed. Please use:

`implementation 'com.emredavarci:CircleProgressBar:1.0.8'`

**Comment by emre1512** [comment] 2019-10-12 18:48
So, I will close this issue tomorrow if there are still no feedbacks. I guess it is fixed.

**Closed as completed** 2019-10-13 14:16 UTC
Labels: bug
